export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
export const GET_TASKS_TODAY_ACTION = "GET_TASKS_TODAY_ACTION";

export const POST_TASK_REQUEST = 'POST_TASK_REQUEST';
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS';
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE';

export const ADD_TASK_ACTION = "ADD_TASK_ACTION";
export const EDIT_TASK_ACTION = "EDIT_TASK_ACTION";
export const DELETE_TASK_ACTION = "DELETE_TASK_ACTION";